INSERT INTO `species`.`species`
(`id`,
`latin_name`,
`latin_name_clean`,
`latin_name_cleanest`,
`common_name`,
`common_name_clean`,
`common_name_cleanest`,
`parent_id`,
`interesting_parent_id`,
`depicted_id`,
`parent_latin_name`,
`depicted_latin_name`,
`rank`,
`extinct`,
`boring`,
`boring_final`,
`shares_sibling_name`,
`image_link`,
`child_count`,
`interesting_child_count`,
`interesting_crunched_ids`,
`linked_image_id`)
VALUES
(
0,
'Arbor vitae',
'Arbor vitae',
'Arbor vitae',
'Tree of Life',
'Tree of Life',
'Tree of Life',
null,
null,
null,
null,
null,
10, -- "Cladus" is generic
0,
0,
0,
null,
'thumb/5/53/Ficus4.jpg/250px-Ficus4.jpg',
null,
null,
null,
null
);
-- this is not needed - as it is already hard-coded
-- update species.species set parent_id = 0 where latin_name in ('Archaea', 'Bacteria', 'Eukaryota', 'Virus');
